// <copyright file="PexTestClass.TestOdysseyGetExistingFaves.g.cs">Copyright ? 2009</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.Pex.Framework.Generated;
using Microsoft.Pex.Framework;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace MyApplication
{
    public partial class PexTestClass
    {
[TestMethod]
[PexGeneratedBy(typeof(PexTestClass))]
public void TestOdysseyGetExistingFaves548()
{
    this.TestOdysseyGetExistingFaves(1);
}
[TestMethod]
[PexGeneratedBy(typeof(PexTestClass))]
public void TestOdysseyGetExistingFaves54802()
{
    IPexChoiceRecorder choices = PexChoose.Replay.Setup();
    choices.DefaultSession
        .At(0, "Num Records", (object)1);
    this.TestOdysseyGetExistingFaves(1);
}
[TestMethod]
[PexGeneratedBy(typeof(PexTestClass))]
public void TestOdysseyGetExistingFaves949()
{
    IPexChoiceRecorder choices = PexChoose.Replay.Setup();
    choices.DefaultSession
        .At(0, "Num Records", (object)1)
        .At(1, "Table: Favorite Column PasswordId Record 0", (object)1);
    this.TestOdysseyGetExistingFaves(2);
}
[TestMethod]
[PexGeneratedBy(typeof(PexTestClass))]
public void TestOdysseyGetExistingFaves54805()
{
    IPexChoiceRecorder choices = PexChoose.Replay.Setup();
    choices.DefaultSession
        .At(0, "Num Records", (object)2);
    this.TestOdysseyGetExistingFaves(1);
}
[TestMethod]
[PexGeneratedBy(typeof(PexTestClass))]
public void TestOdysseyGetExistingFaves54809()
{
    IPexChoiceRecorder choices = PexChoose.Replay.Setup();
    choices.DefaultSession
        .At(0, "Num Records", (object)1)
        .At(1, "Table: Favorite Column PasswordId Record 0", (object)1);
    using (IPexObserveContext observer = PexObserve.NewTest())
    {
      this.TestOdysseyGetExistingFaves(1);
      bool ov2 = observer.GetObservedValue<bool>("2");
      Assert.AreEqual<bool>(true, ov2);
    }
}
[TestMethod]
[PexGeneratedBy(typeof(PexTestClass))]
public void TestOdysseyGetExistingFaves54808()
{
    IPexChoiceRecorder choices = PexChoose.Replay.Setup();
    choices.DefaultSession
        .At(0, "Num Records", (object)1)
        .At(3, "Num Records", (object)1)
        .At(4, "column Name Record 0", "\0");
    this.TestOdysseyGetExistingFaves(1);
}
[TestMethod]
[PexGeneratedBy(typeof(PexTestClass))]
public void TestOdysseyGetExistingFaves54807()
{
    IPexChoiceRecorder choices = PexChoose.Replay.Setup();
    choices.DefaultSession
        .At(0, "Num Records", (object)1)
        .At(2, "Table: Favorite Column FolderId Record 0", (object)1)
        .At(1, "Table: Favorite Column PasswordId Record 0", (object)1);
    using (IPexObserveContext observer = PexObserve.NewTest())
    {
      this.TestOdysseyGetExistingFaves(1);
      bool ov1 = observer.GetObservedValue<bool>("1");
      Assert.AreEqual<bool>(true, ov1);
      bool ov2 = observer.GetObservedValue<bool>("2");
      Assert.AreEqual<bool>(true, ov2);
    }
}
[TestMethod]
[PexGeneratedBy(typeof(PexTestClass))]
public void TestOdysseyGetExistingFaves47101()
{
    IPexChoiceRecorder choices = PexChoose.Replay.Setup();
    choices.DefaultSession
        .At(0, "Num Records", (object)1)
        .At(2, "Table: Favorite Column FolderId Record 0", (object)1)
        .At(1, "Table: Favorite Column PasswordId Record 0", (object)3);
    using (IPexObserveContext observer = PexObserve.NewTest())
    {
      this.TestOdysseyGetExistingFaves(3);
      bool ov1 = observer.GetObservedValue<bool>("1");
      Assert.AreEqual<bool>(true, ov1);
      bool ov2 = observer.GetObservedValue<bool>("2");
      Assert.AreEqual<bool>(true, ov2);
    }
}
[TestMethod]
[PexGeneratedBy(typeof(PexTestClass))]
public void TestOdysseyGetExistingFaves85901()
{
    IPexChoiceRecorder choices = PexChoose.Replay.Setup();
    choices.DefaultSession
        .At(0, "Num Records", (object)1)
        .At(2, "Table: Favorite Column FolderId Record 0", (object)1)
        .At(1, "Table: Favorite Column PasswordId Record 0", (object)4);
    using (IPexObserveContext observer = PexObserve.NewTest())
    {
      this.TestOdysseyGetExistingFaves(4);
      bool ov1 = observer.GetObservedValue<bool>("1");
      Assert.AreEqual<bool>(true, ov1);
      bool ov2 = observer.GetObservedValue<bool>("2");
      Assert.AreEqual<bool>(true, ov2);
    }
}
[TestMethod]
[PexGeneratedBy(typeof(PexTestClass))]
public void TestOdysseyGetExistingFaves45301()
{
    IPexChoiceRecorder choices = PexChoose.Replay.Setup();
    choices.DefaultSession
        .At(0, "Num Records", (object)1)
        .At(2, "Table: Favorite Column FolderId Record 0", (object)1)
        .At(1, "Table: Favorite Column PasswordId Record 0", (object)6);
    using (IPexObserveContext observer = PexObserve.NewTest())
    {
      this.TestOdysseyGetExistingFaves(6);
      bool ov1 = observer.GetObservedValue<bool>("1");
      Assert.AreEqual<bool>(true, ov1);
      bool ov2 = observer.GetObservedValue<bool>("2");
      Assert.AreEqual<bool>(true, ov2);
    }
}
[TestMethod]
[PexGeneratedBy(typeof(PexTestClass))]
public void TestOdysseyGetExistingFaves28701()
{
    IPexChoiceRecorder choices = PexChoose.Replay.Setup();
    choices.DefaultSession
        .At(0, "Num Records", (object)1)
        .At(2, "Table: Favorite Column FolderId Record 0", (object)1)
        .At(1, "Table: Favorite Column PasswordId Record 0", (object)5);
    using (IPexObserveContext observer = PexObserve.NewTest())
    {
      this.TestOdysseyGetExistingFaves(5);
      bool ov1 = observer.GetObservedValue<bool>("1");
      Assert.AreEqual<bool>(true, ov1);
      bool ov2 = observer.GetObservedValue<bool>("2");
      Assert.AreEqual<bool>(true, ov2);
    }
}
[TestMethod]
[PexGeneratedBy(typeof(PexTestClass))]
public void TestOdysseyGetExistingFaves50801()
{
    IPexChoiceRecorder choices = PexChoose.Replay.Setup();
    choices.DefaultSession
        .At(0, "Num Records", (object)1)
        .At(2, "Table: Favorite Column FolderId Record 0", (object)1)
        .At(1, "Table: Favorite Column PasswordId Record 0", (object)7);
    using (IPexObserveContext observer = PexObserve.NewTest())
    {
      this.TestOdysseyGetExistingFaves(7);
      bool ov1 = observer.GetObservedValue<bool>("1");
      Assert.AreEqual<bool>(true, ov1);
      bool ov2 = observer.GetObservedValue<bool>("2");
      Assert.AreEqual<bool>(true, ov2);
    }
}
[TestMethod]
[PexGeneratedBy(typeof(PexTestClass))]
public void TestOdysseyGetExistingFaves83401()
{
    IPexChoiceRecorder choices = PexChoose.Replay.Setup();
    choices.DefaultSession
        .At(0, "Num Records", (object)1)
        .At(2, "Table: Favorite Column FolderId Record 0", (object)1)
        .At(1, "Table: Favorite Column PasswordId Record 0", (object)8);
    using (IPexObserveContext observer = PexObserve.NewTest())
    {
      this.TestOdysseyGetExistingFaves(8);
      bool ov1 = observer.GetObservedValue<bool>("1");
      Assert.AreEqual<bool>(true, ov1);
      bool ov2 = observer.GetObservedValue<bool>("2");
      Assert.AreEqual<bool>(true, ov2);
    }
}
[TestMethod]
[PexGeneratedBy(typeof(PexTestClass))]
public void TestOdysseyGetExistingFaves41101()
{
    IPexChoiceRecorder choices = PexChoose.Replay.Setup();
    choices.DefaultSession
        .At(0, "Num Records", (object)1)
        .At(2, "Table: Favorite Column FolderId Record 0", (object)1)
        .At(1, "Table: Favorite Column PasswordId Record 0", (object)9);
    using (IPexObserveContext observer = PexObserve.NewTest())
    {
      this.TestOdysseyGetExistingFaves(9);
      bool ov1 = observer.GetObservedValue<bool>("1");
      Assert.AreEqual<bool>(true, ov1);
      bool ov2 = observer.GetObservedValue<bool>("2");
      Assert.AreEqual<bool>(true, ov2);
    }
}
[TestMethod]
[PexGeneratedBy(typeof(PexTestClass))]
public void TestOdysseyGetExistingFaves54813()
{
    IPexChoiceRecorder choices = PexChoose.Replay.Setup();
    choices.DefaultSession
        .At(0, "Num Records", (object)1)
        .At(3, "Num Records", (object)1)
        .At(4, "column Name Record 0", new string('\0', 1024))
        .At(17, "Num Records", (object)1)
        .At(20, "column Name Record 0", new string('\0', 1024));
    this.TestOdysseyGetExistingFaves(1);
}
[TestMethod]
[PexGeneratedBy(typeof(PexTestClass))]
public void TestOdysseyGetExistingFaves54814()
{
    IPexChoiceRecorder choices = PexChoose.Replay.Setup();
    choices.DefaultSession
        .At(0, "Num Records", (object)2)
        .At(1, "Table: Favorite Column PasswordId Record 0", (object)1)
        .At(3, "Table: Favorite Column PasswordId Record 1", (object)1)
        .At(5, "Num Records", (object)1)
        .At(6, "column Name Record 0", new string('\0', 512));
    using (IPexObserveContext observer = PexObserve.NewTest())
    {
      this.TestOdysseyGetExistingFaves(1);
      bool ov3 = observer.GetObservedValue<bool>("3");
      Assert.AreEqual<bool>(true, ov3);
    }
}
[TestMethod]
[PexGeneratedBy(typeof(PexTestClass))]
public void TestOdysseyGetExistingFaves54815()
{
    IPexChoiceRecorder choices = PexChoose.Replay.Setup();
    choices.DefaultSession
        .At(0, "Num Records", (object)2)
        .At(2, "Table: Favorite Column FolderId Record 0", (object)1)
        .At(1, "Table: Favorite Column PasswordId Record 0", (object)1)
        .At(4, "Table: Favorite Column FolderId Record 1", (object)1)
        .At(3, "Table: Favorite Column PasswordId Record 1", (object)1)
        .At(5, "Num Records", (object)1)
        .At(6, "column Name Record 0", new string('\0', 512));
    using (IPexObserveContext observer = PexObserve.NewTest())
    {
      this.TestOdysseyGetExistingFaves(1);
      bool ov1 = observer.GetObservedValue<bool>("1");
      Assert.AreEqual<bool>(true, ov1);
      bool ov101 = observer.GetObservedValue<bool>("101");
      Assert.AreEqual<bool>(true, ov101);
      bool ov3 = observer.GetObservedValue<bool>("3");
      Assert.AreEqual<bool>(true, ov3);
    }
}
[TestMethod]
[PexGeneratedBy(typeof(PexTestClass))]
public void TestOdysseyGetExistingFaves94902()
{
    IPexChoiceRecorder choices = PexChoose.Replay.Setup();
    choices.DefaultSession
        .At(0, "Num Records", (object)2)
        .At(1, "Table: Favorite Column PasswordId Record 0", (object)3)
        .At(3, "Table: Favorite Column PasswordId Record 1", (object)1)
        .At(5, "Num Records", (object)1)
        .At(6, "column Name Record 0", new string('\0', 512));
    this.TestOdysseyGetExistingFaves(2);
}
[TestMethod]
[PexGeneratedBy(typeof(PexTestClass))]
public void TestOdysseyGetExistingFaves47102()
{
    IPexChoiceRecorder choices = PexChoose.Replay.Setup();
    choices.DefaultSession
        .At(0, "Num Records", (object)2)
        .At(3, "Table: Favorite Column PasswordId Record 1", (object)2)
        .At(5, "Num Records", (object)1)
        .At(6, "column Name Record 0", new string('\0', 512));
    this.TestOdysseyGetExistingFaves(3);
}
    }
}
