// <copyright file="PexAssemblyInfo.cs">Copyright ? 2009</copyright>
// <auto-generated>
// This file should only contain assembly level attributes.
// Do not add any class or struct definitions as it may disable the ability of the tool to
// update the file.
// </auto-generated>

using System;

using Microsoft.Pex.Framework.Instrumentation;
[assembly: PexInstrumentAssembly("MockDBMS")]
[assembly: PexInstrumentAssembly("ParsedQuery")]
[assembly: PexInstrumentAssembly("MacroScope")]
[assembly: PexInstrumentAssembly("Microsoft.VisualBasic", InstrumentationLevel = PexInstrumentationLevel.Excluded)]